# Generated by Django 4.2 on 2025-11-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='neme',
            new_name='name',
        ),
    ]
