# Generated by Django 4.2 on 2025-11-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='total',
            new_name='percentage',
        ),
    ]
